### ISSUE TITLE
Replace RPC by Indexer API for account/contract page transfers tabs

### ISSUE THREAD

**Issue by tomtomcrypto** [telosnetwork/teloscan#378] opened 2023-02-27 06:59 UTC
## Description

We should replace as many RPC calls as we can on the account/contract page transfers tabs.

## Acceptance

- [ ] The number of RPC is reduced while displaying the same informations

**Comment by karynemayer** [comment] 2023-02-28 16:49
duplicate of #376

**Closed by karynemayer** 2023-02-28 16:49 UTC
Labels: ✨ Enhancement
